name: go test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: go test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.13', '1.14', '1.15', '1.16']

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go

    - uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.32

    - name: Test
      run: go test -v -coverprofile=.coverprofile .

    - name: Report coveralls.io
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: .coverprofile
        flag-name: Go-${{ matrix.go }}
